# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Update Changelog

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 300
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - uses: nrwl/last-successful-commit-action@v1
        id: last_successful_commit
        with:
          branch: 'master'
          workflow_id: 'updateChangelog.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update changelog
        run: ./gradlew updateChangelog
        env:
          SUCCESS_COMMIT: ${{ steps.last_successful_commit.outputs.commit_hash }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update changelog
          commit_user_name: Alex Plate
          commit_user_email: aleksei.plate@jetbrains.com
          commit_author: Alex Plate <aleksei.plate@jetbrains.com>
          file_pattern: CHANGES.md